### ISSUE TITLE
[Feature Request]: rename package name

### ISSUE THREAD

**Issue by Yunuuuu** [pharmaverse/cardinal#189]
### Feature description

There already has a R packge named `falcon` in CRAN: https://cran.r-project.org/web/packages/falcon/index.html. We cannot install two packages with the same name

**Comment by huanlugwu** [comment]
- Option 1: **Herald**
_(To be a sign that something important, and often good, is starting to happen, or to make something publicly known, especially by celebrating or praising it. - https://dictionary.cambridge.org/dictionary/english/herald)_

- Option 2: **Touchstone**
_(An established standard or principle by which something is judged. - https://dictionary.cambridge.org/dictionary/english/touchstone)_

**Comment by telepath37** [comment]
another idea: {cardinal}

rationales: 1) we plan to shift falcon to an ARD-driven table engine/package, and 2)try to follow the bird theme, and "cardinal" has the word "ARD" in it

**Comment by edelarua** [comment]
@telepath37 we're good to proceed with the rename to `cardinal` - it has been approved by the dev team as well.
