### ISSUE TITLE
Update IO website link from falcon to cardinal

### ISSUE THREAD

**Issue by MichaelRimler** [pharmaverse/cardinal#232]
The name change didn't carry forward to https://pharmaverse.github.io/cardinal/

It still resolves to https://pharmaverse.github.io/falcon/

**Comment by edelarua** [comment]
@cicdguy are you able to update this link?

![image](https://github.com/pharmaverse/cardinal/assets/59304861/d89605d0-a766-4a4d-91ad-0ee15c6f31e4)

**Comment by edelarua** [comment]
Thank you!!
